license = "Apache-2.0"
readme = "README.md"
description = "WARNING! UNSTABLE AND WILL BE YANKED! Snapshot of official tigerbeetle client before release"
repository = "https://github.com/jayson-bigpay/tigerbeetle"
documentation = "https://docs.rs/tigerbeetle-rustclient-tests-snapshot"
keywords = ["tigerbeetle"]
categories = ["database"]

[package]
name = "tigerbeetle_rustclient_tests_snapshot"
version = "0.1.0"
edition = "2021"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE*"]
exclude = [".gitignore", "target/", "tests/", "examples/", "samples/"]

[dependencies]
bitflags = "2.6.0"
futures-channel = "0.3.31"

[build-dependencies]
anyhow = "1.0.93"
ignore = "0.4.23"

[dev-dependencies]
anyhow = "1.0.93"
futures = "0.3.31"
